service: lambda-dynamic-ogp-example

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-northeast-1
  stage: ${opt:stage, 'dev'}

plugins:
  - serverless-esbuild
  - serverless-offline

custom:
  esbuild:
    bundle: true
    minify: true
    sourcemap: true
    exclude: []
    target: 'node20'
    platform: 'node'
    concurrency: 10

functions:
  ping:
    handler: src/index.ping
    events:
      - http:
          path: ping
          method: get
          integration: lambda-proxy
          cors: true
